spring:
  datasource:
    url: jdbc:mysql://106.14.239.236:33306/opentest?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: sa
    password: root
  redis:
    host: 106.14.239.236
    port: 6379

logging:
  level:
    com:
      sephiroth:
        mapper: debug

dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://185.250.221.166:2181?init.timeout=60000
  protocol:
    port: 3011
    name: dubbo
  consumer:
    check: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*
